### PR TITLE
Use template to generate sw.js

### LINKED ISSUE #67: Use template to generate sw.js
### Steps to reproduce

1.
2.
3.

### Your environment

* fusion-plugin-service-worker version:

* Node.js version (`node --version`):

* npm version (`npm --version`):

* Operating System:

### PR DESCRIPTION
**Pull request by angus-c**
Resolves #67

### CODE REVIEW

File: src/tokens.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+ * LICENSE file in the root directory of this source tree.
+ *
+ * @flow
+ */
+
+import {createToken} from 'fusion-core';
+
+import type {ConfigTokenType} from './types.js';
+
+export const SWTemplateFunctionToken: ConfigTokenType = createToken(
```
Comment (rtsao) [inline src/tokens.js]: Does the README need to be update with this token?

Comment (angus-c) [reply src/tokens.js]: good catch - updated

**Comment by angus-c** [comment]
!merge
